### ISSUE TITLE
inc\theme-meta.php

### ISSUE THREAD

**Issue by erikdmitchell** [erikdmitchell/koksijde#21]
you can't remove/add:

- [x] meta description - plugin territory
- [x] meta author - plugin territory
- [x] `koksijde_disable_seo_meta()` not really the place for a theme

I would say, most likely, we remove this file

**Comment by erikdmitchell** [comment]
file removed
